Web-Service/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class AdminController : Controller
    {
        //Main panel with clients info
        public async Task<IActionResult> Index()
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync("https://localhost:7245/api/Clients");
                response.EnsureSuccessStatusCode();

                var text = await response.Content.ReadAsStringAsync();
                var clients = JsonConvert.DeserializeObject<List<Client>>(text);

                return View(clients?.ToList());
            }
        }

        #region Delete client's info
        public async Task<IActionResult> DeleteClient(int id)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.DeleteAsync("https://localhost:7245/api/Clients/" + id);
                return RedirectToAction("Index");
            }
        }

        #endregion


        #region Edit client's info

        public async Task<IActionResult> EditExactClient(Client client)
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var newClient = new Client(client.Name, client.Email, client.Message);

                var newClientJson = JsonConvert.SerializeObject(newClient);
                var payload = new StringContent(newClientJson,
                                  Encoding.UTF8, "application/json");

                await httpClient.PutAsync("https://localhost:7245/api/Clients/" +
                                          client.Id, payload);

                return RedirectToAction("Index");
            }
        }


        public async Task<IActionResult> EditPanel(int id)
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync
                    ("https://localhost:7245/api/Clients/" + id);
                response.EnsureSuccessStatusCode();

                var text = await response.Content.ReadAsStringAsync();
                var client = JsonConvert.DeserializeObject<Client>(text);
                return View(client);
            }  
        }

        #endregion

    }
}

Web-Service/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class BlogController : Controller
    {

        #region Basic Set-Up

        private ContentDbContext context;

        public BlogController(ContentDbContext Context)
        {
            context = Context;
        }

        public IActionResult Index()
        {
            return View(context?.BlogPosts?.ToList());
        }

        #endregion

        #region Showing a post
        public IActionResult ShowPost(int id)
        {
            var post = context?.BlogPosts?.Where(context => context.Id == id).FirstOrDefault();
            return View(post);
        }

        #endregion

        #region Adding a post

        public IActionResult AddPostPanel()
        {
            var post = new BlogPost();
            return View(post);
        }

        public IActionResult AddPost(BlogPost post)
        {
            context?.BlogPosts?.Add(post);
            context?.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Deleting a post

        public IActionResult DeletePost(int id)
        {
            var post = context?.BlogPosts?.Where(p => p.Id == id).FirstOrDefault();
            if (post != null)
            {
                context?.BlogPosts?.Remove(post);
                context?.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion
    }
}

Web-Service/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class ProjectsController : Controller
    {
        #region Basic Set-Up

        private ContentDbContext context;
        public ProjectsController(ContentDbContext Context)
        {
            context = Context;
        }
        
        public IActionResult Index()
        {
            return View(context?.Projects?.ToList());
        }

        #endregion

        #region Displaing a single project
        public IActionResult ShowProject(int id)
        {
            var proj = context?.Projects?.Where(p => p.Id == id).FirstOrDefault();
            return View(proj);
        }
        #endregion

        #region Adding a project
        public IActionResult AddProjectPanel()
        {
            Project proj = new Project();
            return View(proj);
        }

        public IActionResult AddProject(Project proj)
        {
            context?.Projects?.Add(proj);
            context?.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Deleting a project

        public IActionResult DeleteProject(int id)
        {
            var proj = context?.Projects?.Where(p => p.Id == id).FirstOrDefault();
            if (proj != null)
            {
              context?.Projects?.Remove(proj);
              context?.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion
    }
}

Web-Service/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class ServicesController : Controller
    {
        #region Basic Set-Up

        private ContentDbContext context;
        public ServicesController(ContentDbContext Context)
        {
            context = Context;
        }

        public IActionResult Index()
        {
            return View(context?.Services?.ToList());
        }

        #endregion

        #region Adding a Service 
        public IActionResult AddServicePanel()
        {
            Service service = new Service();
            return View(service);
        }

        public IActionResult AddService(Service service)
        {
            context?.Services?.Add(service);
            context?.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Deleting a Service
        public IActionResult DeleteService(int id)
        {
            var serv = context?.Services?.Where(p => p.Id == id).FirstOrDefault();
            if (serv != null)
            {
                context?.Services?.Remove(serv);
                context?.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion
    }
}

Web-Service/Views/Admin/EditPanel.cshtml
@model Client;

<h2 class="title">EditPanel</h2>

<div class="row">
	<div class="col-6">
	<form asp-controller="Admin" asp-action="EditExactClient" asp-route-id="@Model.Id">
		<div>
		 <label class="form-label"></label>
		 <input asp-for="@Model.Name" type ="text" class="form-control"/>
		</div>

	   <div>
		<label class="form-label"></label>
		<input  asp-for="@Model.Email" type ="email" class="form-control" />
	   </div>

		<div>
		 <label class="form-label"></label>
		 <input asp-for="@Model.Message"  type ="text" class="form-control"/>
		</div>

		<div>
		<button type="submit" class="btn btn-outline-primary">
			Edit
	    </button>
		</div>

	 </form>
	</div>
 </div>

Web-Service/Views/Admin/Index.cshtml
@model List<Client>;

<h2 class="title">Admin panel</h2>
<br />

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Message</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
      @foreach(var client in Model){
          <tr>
          <th scope="row">@client.Id</th>
          <td>@client.Name</td>
          <td>@client.Email</td>
          <td>@client.Message</td>
          <td>
           <a asp-controller="Admin"
              asp-action="EditPanel" asp-route-id="@client.Id" class="btn btn-primary">
              Edit
           </a>  
            <a asp-controller="Admin"
              asp-action="DeleteClient" asp-route-id="@client.Id" class="btn btn-primary">
               Delete
            </a> 
          </td>
        </tr>
      }

      <a asp-controller="Projects"
       asp-action="AddProjectPanel" class="btn btn-primary">
         Add a Project
       </a>

       <a asp-controller="Services"
       asp-action="AddServicePanel" class="btn btn-primary">
         Add a Service
       </a>

      <a asp-controller="Blog"
       asp-action="AddPostPanel" class="btn btn-primary">
         Add a Post
       </a>
  </tbody>
</table>