Web-Service/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class AdminController : Controller
    {
        //Main panel with clients info
        public async Task<IActionResult> Index()
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync("https://localhost:7245/api/Clients");
                response.EnsureSuccessStatusCode();

                var text = await response.Content.ReadAsStringAsync();
                var clients = JsonConvert.DeserializeObject<List<Client>>(text);

                return View(clients?.ToList());
            }
        }

        #region Delete client's info
        public async Task<IActionResult> DeleteClient(int id)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.DeleteAsync("https://localhost:7245/api/Clients/" + id);
                return RedirectToAction("Index");
            }
        }

        #endregion


        #region Edit client's info

        public async Task<IActionResult> EditExactClient(Client client)
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var newClient = new Client(client.Name, client.Email, client.Message);

                var newClientJson = JsonConvert.SerializeObject(newClient);
                var payload = new StringContent(newClientJson,
                                  Encoding.UTF8, "application/json");

                await httpClient.PutAsync("https://localhost:7245/api/Clients/" +
                                          client.Id, payload);

                return RedirectToAction("Index");
            }
        }


        public async Task<IActionResult> EditPanel(int id)
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync
                    ("https://localhost:7245/api/Clients/" + id);
                response.EnsureSuccessStatusCode();

                var text = await response.Content.ReadAsStringAsync();
                var client = JsonConvert.DeserializeObject<Client>(text);
                return View(client);
            }  
        }

        #endregion

    }
}

Web-Service/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class BlogController : Controller
    {

        #region Basic Set-Up

        private ContentDbContext context;

        public BlogController(ContentDbContext Context)
        {
            context = Context;
        }

        public IActionResult Index()
        {
            return View(context?.BlogPosts?.ToList());
        }

        #endregion

        #region Showing a post
        public IActionResult ShowPost(int id)
        {
            var post = context?.BlogPosts?.Where(context => context.Id == id).FirstOrDefault();
            return View(post);
        }

        #endregion

        #region Adding a post

        public IActionResult AddPostPanel()
        {
            var post = new BlogPost();
            return View(post);
        }

        public IActionResult AddPost(BlogPost post)
        {
            context?.BlogPosts?.Add(post);
            context?.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Deleting a post

        public IActionResult DeletePost(int id)
        {
            var post = context?.BlogPosts?.Where(p => p.Id == id).FirstOrDefault();
            if (post != null)
            {
                context?.BlogPosts?.Remove(post);
                context?.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion
    }
}

Web-Service/Controllers/LogInController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;

namespace Web_Service.Controllers
{
    public class LogInController : Controller
    {
        #region Basic set-up

        private readonly SignInManager<IdentityUser> SignInManager;
        private readonly UserManager<IdentityUser> UserManager;

        public LogInController(SignInManager<IdentityUser> signInManager, 
                               UserManager<IdentityUser> userManager)
        {
            SignInManager = signInManager;
            UserManager = userManager;
        }

        #endregion

        public IActionResult Index()
        {
            LogInUser logInUser = new LogInUser();
            return View(logInUser);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoggingIn(LogInUser logInUser)
        {
            if (ModelState.IsValid)
            {
                var identityRes = await SignInManager.PasswordSignInAsync(logInUser.UserName,
                                                                          logInUser.Password,
                                                                          logInUser.RememberMe,
                                                                          false);

                if (identityRes.Succeeded)
                    return RedirectToAction("Index", "Main", new { area = "" });
                else
                    ModelState.AddModelError("", "Invalid");

            }

            return RedirectToAction("Index");
        }
    }
}

Web-Service/Controllers/MainController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Web_Service.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace Web_Service.Controllers
{
    public class MainController : Controller
    {
        
        
        public IActionResult Index()
        {
            Client client = new Client();
            return View(client);
        }

        public async Task<IActionResult> AddClient(Client client)
        {
            using(HttpClient httpClient = new HttpClient())
            {
                var newClientJson = JsonConvert.SerializeObject(client);
                var payload = new StringContent(newClientJson, Encoding.UTF8,
                                                               "application/json");
                await httpClient.PostAsync("https://localhost:7245/api/Clients", payload);
            }

            return RedirectToAction("Index");
        }
    }
}

Web-Service/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> userManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_Service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_Service.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/main-page.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/projects.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/services.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/contacts.css" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skill-Consalt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                    </ul>

                        @if(signInManager.IsSignedIn(User))
                        {
                          <ul class="navbar-nav flex-grow-right">
                             <li class="nav-item">
                               <a class="nav-link text-dark" 
                               asp-area="" asp-controller="LogOut" asp-action="Index">
                                Log Out
                               </a>
                             </li>
                          </ul>
                        } 
                        else
                        {
                           <ul class="navbar-nav flex-grow-right">
                            <li class="nav-item">
                               <a class="nav-link text-dark" asp-area=""
                                asp-controller="Register" asp-action="Index">
                                  Register
                               </a>
                             </li>
                             <li class="nav-item">
                               <a class="nav-link text-dark" asp-area=""
                                asp-controller="LogIn" asp-action="Index">
                                  Log in
                               </a>
                             </li>
                           </ul>
                         
                        }

                        @if (userManager.GetUserName(User) == "admin1")
                        {
                           <ul class="navbar-nav flex-grow-right">
                              <li class="nav-item">
                               <a class="nav-link text-dark" 
                                asp-area="" asp-controller="Admin" asp-action="Index">
                                Admin Panel
                               </a>
                             </li>
                           </ul>
                        }
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web_Service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>